### ISSUE TITLE
[BUG] : Installation using evironment.yml failed

### ISSUE THREAD

**Issue by alberto-battistel** [EISy-as-Py/hardy#15] opened 2022-01-26 16:08 UTC
**Describe the bug**
The Installation using evironment.yml (Recommended) failed. 

**To Reproduce**
Situation 1:
Download the 'evironment.yml' and run:

`conda install --name hardy --file environment.yml`

gives:

> EnvironmentLocationNotFound: Not a conda environment: /home/alberto/anaconda3/envs/hardy

Situation 2:
Clone the repository:

`git clone https://github.com/EISy-as-Py/hardy.git`

and run:
`cd hardy`
`conda install --name hardy --file environment.yml`

gives:

> EnvironmentLocationNotFound: Not a conda environment: /home/alberto/anaconda3/envs/hardy

Create the environment: 

`conda create --name hardy`

and run: 

`conda install --name hardy --file environment.yml`

still fails with:

> CondaValueError: could not parse 'name: hardy' in: environment.yml

**Expected behavior**
Maybe I am doing something fundamentally stupid, but I cannot succeed in installing this package.

**System information**

> OS: Manjaro Linux x86_64
> Host: 20AWS1J001 ThinkPad T440p
> Kernel: 5.4.173-1-MANJARO
> conda 4.11.0

**Comment by amoeez** [comment] 2022-01-26 16:21
Hi @alberto-battistel,
Can you let me know the python version you're using?

**Comment by alberto-battistel** [comment] 2022-01-26 16:25
Hi,
Python 3.8.3
Is this the problem?

**Comment by amoeez** [comment] 2022-01-26 16:36
That would be an issue while resolving the dependencies, though for this particular issue, the alternate is creating the environment using
`conda env create -f environment.yml`
after you clone the repository and change the folder in situation 2

**Comment by alberto-battistel** [comment] 2022-01-28 18:53
Ok, `conda env create -f environment.yml` works.
Python version in the environment is

> Python 3.7.12

However, after activating the environment and running

`conda install -c pozzorg hardy`

I get: 

> Collecting package metadata (current_repodata.json): done
> Solving environment: failed with initial frozen solve. Retrying with flexible solve.
> Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
> Collecting package metadata (repodata.json): done
> Solving environment: failed with initial frozen solve. Retrying with flexible solve.
> Solving environment: \ 
> Found conflicts! Looking for incompatible packages.
> This can take several minutes.  Press CTRL-C to abort.
> failed                                                                                                                                                       
> 
> UnsatisfiableError: The following specifications were found to be incompatible with each other:
> 
> Output in format: Requested package -> Available versionsThe following specifications were found to be incompatible with your system:
> 
>   - feature:/linux-64::__glibc==2.33=0
>   - feature:|@/linux-64::__glibc==2.33=0
> 
> Your installed version is: 2.33

**Comment by amoeez** [comment] 2022-01-29 02:14
Hi @alberto-battistel,

It appears conda is having conflicts with some already installed libraries on your OS. Although the version of dependencies appears the same, I'm unable to trace the root cause at the moment. I'll keep this issue open and meanwhile it is resolved, you should be able to install it either with `pip install .` or `python3.7 setup.py install` from the hardy directory.

Thank you for your patience.

**Comment by alberto-battistel** [comment] 2022-01-30 16:21
ok, `pip install .` works

**Closed as completed** 2022-02-11 17:32 UTC
Labels: bug
